export enum ProductOperatorLogType {
  MarketCreationFeeToken,
  MarketCreationFee,
  DefaultRatesOracle,
  WithdrawDelay,
  WithdrawRequestExpiration,
  WaitingPeriod,
  CoverAdjusterOracle,
  DefaultCapitalToken,
  DefaultPremiumToken,
  ClaimProcessor,
  PayoutRequester,
  PayoutApprover,
  MarketCreatorsAllowlistId,
}
